// A booking for tomorrow checked in with "Check in anyway", then its pass changed: another pass by code, Undo
// pass, the saved pass again. Before the fix the old pass came off and the new one never went on.
// Usage: LAIR_AT=2026-10-04T23:30 node forced.mjs phone|desktop
import { m, chromium, open, shot, text, overflow, smallTargets, STAFF, CUSTOMER, PORT } from './lib.mjs';
const tag = process.argv[2] || 'phone';
const server = await m.serve(PORT);
const browser = await chromium.launch();
m.mockState.customer = CUSTOMER;
const { ctx, page } = await open(browser, tag, '/pages/book-a-table');
const log = (...a) => console.log(tag, '|', ...a);
const sleep = (ms) => page.waitForTimeout(ms);
const card = () => text(page, '[data-checkin-result]');
const state = (ref) => page.evaluate((r) => {
  const b = window.Lair.store.data.bookings.find((x) => x.ref === r);
  const passes = window.Lair.store.backend.passList().map((p) => `${p.label.split(':')[0]}:${p.sessionsTotal - p.sessionsUsed}`).join(', ');
  return `${b ? `due ${b.due} covered ${b.covered} pass ${b.pass && b.pass.code} status ${b.status}` : 'no booking'} | ${passes}`;
}, ref);
await page.waitForSelector('[data-pass]:not([hidden])', { timeout: 4000 }).catch(() => log('NO PASS TOGGLE'));
await page.click('[data-slot]:not([disabled])');
await sleep(250);
for (let i = 0; i < 2; i += 1) await page.click('[data-stepper="people"] [data-step-up]');
await page.click('.booking__pass .booking__toggle');
await sleep(250);
log('booking:', await text(page, '[data-summary]'));
await page.click('[data-submit]');
await sleep(900);
const ref = await text(page, '.ticket-qr__ref');
m.mockState.customer = STAFF;
await page.goto(`http://localhost:${PORT}/pages/lair-staff`, { waitUntil: 'networkidle' });
await sleep(600);
await page.fill('#checkin-code', ref);
await page.press('#checkin-code', 'Enter');
await sleep(600);
log('scanned:', await card());
log('not today card buttons:', (await page.$$eval('[data-checkin-result] button', (b) => b.map((x) => x.textContent.trim()))).join(' / '));
await page.evaluate(() => document.querySelector('.checkin').scrollIntoView({ block: 'start' }));
await shot(page, `${tag}-f1-not-today`, '.checkin');
await page.click('[data-checkin-force]');
await sleep(600);
log('checked in anyway:', await state(ref));
const league = await page.evaluate(() => window.Lair.store.backend.passList().find((p) => p.label === 'Warhammer league').code);
await page.click('[data-pass-other]');
await sleep(200);
await page.fill('#checkin-pass-code', league);
await page.click('[data-pass-use] button[type="submit"]');
await sleep(700);
log('league pass:', (await card()).slice(0, 260));
log('  →', await state(ref));
await shot(page, `${tag}-f2-league`, '.checkin');
await page.click('[data-pass-undo]');
await sleep(700);
log('undo:', await state(ref));
await page.click('[data-pass-saved]');
await sleep(700);
log('saved again:', (await card()).slice(0, 200));
log('  →', await state(ref));
log('overflow', await overflow(page), 'small', JSON.stringify(await smallTargets(page, '[data-checkin-result]')));
log('errors', JSON.stringify(page.errors));
await ctx.close();
await browser.close();
server.close();
