import { serve } from './render.mjs';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require('/opt/node-tools/node_modules/playwright');
const server = await serve(4177);
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const errors = [];
const page = await ctx.newPage();
page.on('pageerror', (e) => errors.push('book: ' + e.message));
await page.goto('http://localhost:4177/pages/book-a-table', { waitUntil: 'networkidle' });
await page.waitForTimeout(600);
// pick tomorrow, first enabled slot
await page.click('.date-chip:not([disabled]) >> nth=1');
await page.click('[data-play-start]:not([disabled]), [data-slot]:not([disabled]) >> visible=true >> nth=0');
await page.check('input[name="extra"][value="wargame"]');
await page.waitForTimeout(200);
const picked = await page.textContent('[data-picked]');
await page.fill('#bk-name', 'Test Goblin');
await page.fill('#bk-email', 'test@example.com');
await page.click('input[name="pay"][value="now"]');
const btn = await page.textContent('[data-submit]');
await page.click('[data-submit]');
await page.waitForTimeout(500);
const ticket = await page.textContent('[data-done]').catch(() => '');
console.log('picked:', picked.replace(/\s+/g, ' ').trim());
console.log('submit label:', btn);
console.log('ticket:', ticket.replace(/\s+/g, ' ').slice(0, 220));
// staff
const staff = await ctx.newPage();
staff.on('pageerror', (e) => errors.push('staff: ' + e.message));
await staff.goto('http://localhost:4177/pages/lair-staff', { waitUntil: 'networkidle' });
await staff.waitForTimeout(600);
await staff.click('[data-table="T2"]');
await staff.fill('#walkin-name', 'Walky');
await staff.click('[data-walkin-form] button[type="submit"]');
await staff.waitForTimeout(400);
const t2 = await staff.getAttribute('[data-table="T2"]', 'data-status');
await staff.click('[data-table="T2"]');
await staff.click('[data-act="move"]');
await staff.click('[data-table="T6"]');
await staff.waitForTimeout(400);
const t2b = await staff.getAttribute('[data-table="T2"]', 'data-status');
const t6 = await staff.getAttribute('[data-table="T6"]', 'data-status');
const bar = (await staff.textContent('[data-bar]')).replace(/\s+/g, ' ');
console.log('T2 after seat:', t2, '| after move T2:', t2b, 'T6:', t6);
console.log('bar:', bar.slice(0, 200));
// public map in first tab should see T6 busy via storage sync
await page.reload({ waitUntil: 'networkidle' });
await page.waitForTimeout(500);
console.log('public T6:', await page.getAttribute('[data-table="T6"]', 'data-status'));
console.log('errors:', errors);
await browser.close(); server.close();
