import { serve } from './render.mjs';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require('/opt/node-tools/node_modules/playwright');
const server = await serve(4179);
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 390, height: 844 } })).newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
await page.goto('http://localhost:4179/pages/gm-games', { waitUntil: 'networkidle' });
await page.waitForTimeout(700);
await page.click('[data-game] >> nth=0');
await page.waitForTimeout(300);
await page.fill('#join-name', 'Phone Player');
await page.fill('#join-email', 'phone@example.com');
const label = await page.textContent('[data-join-submit]');
await page.click('[data-join-submit]');
await page.waitForTimeout(600);
const done = (await page.textContent('gm-board dialog')).replace(/\s+/g, ' ');
console.log('button:', label.trim());
console.log('joined:', done.slice(0, 260));
const overflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth);
console.log('phone overflow px:', overflow, '| errors:', errors);
await browser.close(); server.close();
